### ISSUE TITLE
Описание протокола

### ISSUE THREAD

**Issue by drewxa** [Librarians-Squad/tezos-p2p-scanner#1]
Ждем объяснение протокола на пальцах с помощью русского языка в README.md

**Comment by mocurin** [comment]
[Готово](https://gist.github.com/mocurin/392699aa52b72aa658e4ae42a67f6cdd). Опустил часть про bootsrapping, не уверен что пригодится.

**Comment by drewxa** [comment]
и вот тут есть https://gist.github.com/drewxa/50b2822c35696f73760eab040a1360e0
