### ISSUE TITLE
Реализация p2p уровня на Go

### ISSUE THREAD

**Issue by AndreevSemen** [Librarians-Squad/tezos-p2p-scanner#4]
### Что требуется

Необходимо прописать всю логику сканера на уровне p2p, который использовал бы библиотеку `ocaml->go` для работы с функциями от tezos (это скорее всего только `generate_identity`, но могут возникнуть потребность в других функциях).

### Задачи
- [ ] Изучить протокол
  - [ ] UML диаграмма handshaking
  - [ ] Изучение хедеров, с помощью которых общаются ноды
- [ ] Описать подробный алгоритм работы сканера
- [ ] Создание UML диаграммы сканера
- [x] Реализовать handshake между двумя нодами
- [x] Реализовать сбор необходмой информации от известной ноды

### Сроки и распределение обязанностей

- [x] Определить кто будет раотать над этой частью проекта (предположительно @sergejkoll и @AndreevSemen )
- [ ] Установить сроки для каждой из задач (описание алгоритма примерно до 31.03.2020 (вторник), UML диаграмма еще неделя (07.04.2020), далее пока не оценено)

**Comment by drewxa** [comment]
done
